# Generated by Django 3.2.5 on 2021-08-10 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userLoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 8, 10, 17, 32, 0, 567022, tzinfo=utc))),
                ('gender', models.CharField(max_length=15)),
                ('married', models.CharField(max_length=5)),
                ('dependents', models.CharField(max_length=5)),
                ('education', models.CharField(max_length=20)),
                ('employment', models.CharField(max_length=10)),
                ('income', models.IntegerField()),
                ('coappIncome', models.IntegerField()),
                ('loanAmount', models.IntegerField()),
                ('loanAmountTerm', models.IntegerField()),
                ('creditHistory', models.IntegerField()),
                ('area', models.CharField(max_length=15)),
                ('assets', models.IntegerField()),
                ('loanStatus', models.CharField(max_length=15)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.userdetails')),
            ],
        ),
    ]
