# Generated by Django 3.2.5 on 2021-08-12 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminusername', models.CharField(max_length=100)),
                ('adminpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userloandetails',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 12, 14, 5, 47, 425262, tzinfo=utc)),
        ),
    ]
